In [3]:
import torch
import numpy as np

### Tensors

Creating Numpy Array

In [4]:
## Making Tensors from the numpy 
list_number = [1, 2, 3, 4, 5]
numpy_array = np.array(list_number)
numpy_array, type(numpy_array)

(array([1, 2, 3, 4, 5]), numpy.ndarray)

In [5]:
x = torch.from_numpy(numpy_array)
x, type(x)

(tensor([1, 2, 3, 4, 5]), torch.Tensor)

Using `arange` to create a numpy array:

In [6]:
x = torch.arange(0, 10, 1)
x

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

`reshape`

In [7]:
y = x.reshape(2, 5)
y, type(y)

(tensor([[0, 1, 2, 3, 4],
         [5, 6, 7, 8, 9]]),
 torch.Tensor)

`reshape` with `-1` to infer dimension:

In [12]:
z = x.reshape(-1, 5)
z, type(z)

(tensor([[0, 1, 2, 3, 4],
         [5, 6, 7, 8, 9]]),
 torch.Tensor)

In [11]:
h = x.reshape(2, -1)
h, type(h)

(tensor([[0, 1, 2, 3, 4],
         [5, 6, 7, 8, 9]]),
 torch.Tensor)

Initializing a tensor with zeros or ones

In [15]:
x= torch.zeros((2, 3))
x, type(x)

(tensor([[0., 0., 0.],
         [0., 0., 0.]]),
 torch.Tensor)

In [16]:
y=torch.ones((2, 3))
y, type(y)

(tensor([[1., 1., 1.],
         [1., 1., 1.]]),
 torch.Tensor)

Generating a random tensor

In [29]:
torch.manual_seed(0)  # For reproducibility
x = torch.rand((2, 3))
x, type(x)

(tensor([[0.4963, 0.7682, 0.0885],
         [0.1320, 0.3074, 0.6341]]),
 torch.Tensor)

Creating tensors with specific values:

In [30]:
torch.tensor([[1, 2, 3], [4, 5, 6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

Indexing and slicing tensors

In [40]:
x = torch.arange(0, 9, 1)
x, type(x)

(tensor([0, 1, 2, 3, 4, 5, 6, 7, 8]), torch.Tensor)

In [43]:
x = x.reshape(3, -1)

In [44]:
x

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

Indexing 

In [45]:
x[-1]

tensor([6, 7, 8])

In [46]:
x[:2]

tensor([[0, 1, 2],
        [3, 4, 5]])

Writing values to specific indices

In [48]:
x[1, 1] = 10

In [49]:
x

tensor([[ 0,  1,  2],
        [ 3, 10,  5],
        [ 6,  7,  8]])

In [50]:
x[1][1] = 20
x

tensor([[ 0,  1,  2],
        [ 3, 20,  5],
        [ 6,  7,  8]])

Assigning a range of values 

In [51]:
#assigning the first column as all ones
x[:, 0] = 1
x

tensor([[ 1,  1,  2],
        [ 1, 20,  5],
        [ 1,  7,  8]])

In [52]:
#assigning the last column first 2 rows as all zeros
x[0:2, -1] = 0
x

tensor([[ 1,  1,  0],
        [ 1, 20,  0],
        [ 1,  7,  8]])

Operations on Tensors:
In general, operations on tensors are applied element-wise. For example, if `x` and `y` are tensors, then:

In [53]:
x = torch.rand(1, 5)
y = torch.rand(1, 5)
x,y

(tensor([[0.4901, 0.8964, 0.4556, 0.6323, 0.3489]]),
 tensor([[0.4017, 0.0223, 0.1689, 0.2939, 0.5185]]))

Operations

In [54]:
x*y, x/y, x+y, x-y

(tensor([[0.1969, 0.0200, 0.0769, 0.1858, 0.1809]]),
 tensor([[ 1.2200, 40.1529,  2.6983,  2.1515,  0.6729]]),
 tensor([[0.8918, 0.9188, 0.6245, 0.9262, 0.8674]]),
 tensor([[ 0.0884,  0.8741,  0.2868,  0.3384, -0.1696]]))

Performing Linear Algebra Operations

In [55]:
X = torch.arange(0, 10, 1).reshape(2, 5)
Y = torch.arange(10, 20, 1).reshape(2, 5)
X, Y

(tensor([[0, 1, 2, 3, 4],
         [5, 6, 7, 8, 9]]),
 tensor([[10, 11, 12, 13, 14],
         [15, 16, 17, 18, 19]]))

`cat` operation

In [58]:
Z_dim0 = torch.cat((X, Y), dim=0)
Z_dim1 = torch.cat((X, Y), dim=1)
Z_dim0, Z_dim1

(tensor([[ 0,  1,  2,  3,  4],
         [ 5,  6,  7,  8,  9],
         [10, 11, 12, 13, 14],
         [15, 16, 17, 18, 19]]),
 tensor([[ 0,  1,  2,  3,  4, 10, 11, 12, 13, 14],
         [ 5,  6,  7,  8,  9, 15, 16, 17, 18, 19]]))

Using `sum` to sum across all dimensions resulting in a scalar

In [59]:
torch.sum(Z_dim0), torch.sum(Z_dim1)

(tensor(190), tensor(190))

### Broadcasting

When we do broadcasting, we can add a tensor of shape `(3, 1)` to a tensor of shape `(1, 2)`. The first tensor is broadcasted across the second dimension, and the second tensor is broadcasted across the first dimension.

In [61]:
a = torch.tensor([0,1,2]).reshape(3, 1)
b = torch.tensor([4,5]).reshape(1, 2)
a, b

(tensor([[0],
         [1],
         [2]]),
 tensor([[4, 5]]))

In [62]:
a+b

tensor([[4, 5],
        [5, 6],
        [6, 7]])

### Saving Memory

When we creatre tensors and perform some operations, i.e Y= Y+X, the new memory location is created for Y. We can't do like go around and allocate memory unnecessarily. We can use `Y+=X` to save memory. This is called in-place operation.

In [71]:
before = id(Y)
Y = Y + X
after = id(Y)
before == after

False

In [72]:
before_ = id(X)
X += Y
after_ = id(X)
after_ == before_

True

Conversion of other python objects

In [ ]:
a = torch.tensor([3.5])
a, a.item(), float(a), int(a)

(tensor([3.5000]), 3.5, 3.5, 3)

In [75]:
X <= Y

tensor([[False, False, False, False, False],
        [False, False, False, False, False]])

In [77]:
a = torch.arange(0, 9, 1).reshape(3, 3)
b = torch.tensor([4, 5, 6]).reshape(3, 1)
a, b

(tensor([[0, 1, 2],
         [3, 4, 5],
         [6, 7, 8]]),
 tensor([[4],
         [5],
         [6]]))

In [78]:
a+b

tensor([[ 4,  5,  6],
        [ 8,  9, 10],
        [12, 13, 14]])